services:
  - type: web
    name: changi-airport-chatbot
    env: python
    plan: free
    buildCommand: |
  pip install --upgrade pip &&
  pip install --no-cache-dir --find-links https://download.pytorch.org/whl/cpu/torch_stable.html torch==2.1.1+cpu torchvision==0.16.1+cpu torchaudio==2.1.1+cpu &&
  pip install --no-cache-dir -r requirements.txt &&
  python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')"
    startCommand: python main.py
    healthCheckPath: /health
    envVars:
      - key: SENTENCE_TRANSFORMERS_HOME
        value: /opt/render/project/src/models
      - key: TRANSFORMERS_CACHE
        value: /opt/render/project/src/models
      - key: HF_HOME
        value: /opt/render/project/src/models
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TORCH_HOME
        value: /opt/render/project/src/models/torch
      - key: PINECONE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: INDEX_NAME
        value: airportchatbot
    disk:
      name: models-cache
      mountPath: /opt/render/project/src/models
      sizeGB: 2
